/**
 * AUTO-GENERATED by scripts/build-product-catalog-doc-pages.mjs
 * Do not edit by hand — re-run the script after adding/updating PDFs.
 */
export const PRODUCT_CATALOG_DOC_PAGES: Readonly<Record<string, readonly string[]>> = {
  "blanco-blanco-diamond-50-50": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-50-50/page-1.png"
  ],
  "blanco-blanco-diamond-50-50-low-divide": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-50-50-low-divide/page-1.png"
  ],
  "blanco-blanco-diamond-50-50-low-divide-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-50-50-low-divide-sinks/page-1.png"
  ],
  "blanco-blanco-diamond-50-50-regular-divide": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-50-50-regular-divide/page-1.png"
  ],
  "blanco-blanco-diamond-60-40-low-divide-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-60-40-low-divide-sinks/page-1.png"
  ],
  "blanco-blanco-diamond-60-40-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-60-40-sinks/page-1.png"
  ],
  "blanco-blanco-diamond-60-40-sinks-low-divide": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-60-40-sinks-low-divide/page-1.png"
  ],
  "blanco-blanco-diamond-60-40-sinks-regular-divide": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-60-40-sinks-regular-divide/page-1.png"
  ],
  "blanco-blanco-diamond-small-bar-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-diamond-small-bar-sinks/page-1.png"
  ],
  "blanco-blanco-ikon-apron-front-single-bowl": [
    "/product-catalog/doc-pages/blanco-blanco-ikon-apron-front-single-bowl/page-1.png"
  ],
  "blanco-blanco-liven-laundry-12-depth": [
    "/product-catalog/doc-pages/blanco-blanco-liven-laundry-12-depth/page-1.png"
  ],
  "blanco-blanco-precis-21-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-precis-21-sinks/page-1.png"
  ],
  "blanco-blanco-precis-24-sink": [
    "/product-catalog/doc-pages/blanco-blanco-precis-24-sink/page-1.png"
  ],
  "blanco-blanco-precis-27-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-precis-27-sinks/page-1.png"
  ],
  "blanco-blanco-precis-30-single-bowl": [
    "/product-catalog/doc-pages/blanco-blanco-precis-30-single-bowl/page-1.png"
  ],
  "blanco-blanco-precis-50-50-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-precis-50-50-sinks/page-1.png"
  ],
  "blanco-blanco-precis-60-40-sinks-low-divide": [
    "/product-catalog/doc-pages/blanco-blanco-precis-60-40-sinks-low-divide/page-1.png"
  ],
  "blanco-blanco-precis-60-40-sinks-regular-divide": [
    "/product-catalog/doc-pages/blanco-blanco-precis-60-40-sinks-regular-divide/page-1.png"
  ],
  "blanco-blanco-precis-bar-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-precis-bar-sinks/page-1.png"
  ],
  "blanco-blanco-precis-super-single-sinks": [
    "/product-catalog/doc-pages/blanco-blanco-precis-super-single-sinks/page-1.png"
  ],
  "blanco-blanco-super-single": [
    "/product-catalog/doc-pages/blanco-blanco-super-single/page-1.png"
  ],
  "blanco-inteos-33-workstation": [
    "/product-catalog/doc-pages/blanco-inteos-33-workstation/page-1.png",
    "/product-catalog/doc-pages/blanco-inteos-33-workstation/page-2.png"
  ],
  "faucet-delta-1930-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-1930-ar-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-1930-ar-dst/page-2.png"
  ],
  "faucet-delta-1940-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-1940-ar-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-1940-ar-dst/page-2.png"
  ],
  "faucet-delta-1960-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-1960-ar-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-1960-ar-dst/page-2.png"
  ],
  "faucet-delta-19802z-sp-dst": [
    "/product-catalog/doc-pages/faucet-delta-19802z-sp-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-19802z-sp-dst/page-2.png"
  ],
  "faucet-delta-3559-sspd-dst": [
    "/product-catalog/doc-pages/faucet-delta-3559-sspd-dst/page-1.png"
  ],
  "faucet-delta-4153-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-4153-ar-dst/page-1.png"
  ],
  "faucet-delta-559lf-blmpu": [
    "/product-catalog/doc-pages/faucet-delta-559lf-blmpu/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-559lf-blmpu/page-2.png"
  ],
  "faucet-delta-9085-ar-pr-dst": [
    "/product-catalog/doc-pages/faucet-delta-9085-ar-pr-dst/page-1.png"
  ],
  "faucet-delta-9113-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-9113-ar-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9113-ar-dst/page-2.png"
  ],
  "faucet-delta-9159-cz-dst": [
    "/product-catalog/doc-pages/faucet-delta-9159-cz-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9159-cz-dst/page-2.png"
  ],
  "faucet-delta-9159-tlv-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-9159-tlv-ar-dst/page-1.png"
  ],
  "faucet-delta-9176-cz-pr-dst": [
    "/product-catalog/doc-pages/faucet-delta-9176-cz-pr-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9176-cz-pr-dst/page-2.png"
  ],
  "faucet-delta-9178-dst": [
    "/product-catalog/doc-pages/faucet-delta-9178-dst/page-1.png"
  ],
  "faucet-delta-9179-dst": [
    "/product-catalog/doc-pages/faucet-delta-9179-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9179-dst/page-2.png"
  ],
  "faucet-delta-9191-bl-dst": [
    "/product-catalog/doc-pages/faucet-delta-9191-bl-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9191-bl-dst/page-2.png"
  ],
  "faucet-delta-9659-ks-dst": [
    "/product-catalog/doc-pages/faucet-delta-9659-ks-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9659-ks-dst/page-2.png"
  ],
  "faucet-delta-9959-bl-dst": [
    "/product-catalog/doc-pages/faucet-delta-9959-bl-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta-9959-bl-dst/page-2.png"
  ],
  "faucet-delta-9986-ar-dst": [
    "/product-catalog/doc-pages/faucet-delta-9986-ar-dst/page-1.png"
  ],
  "faucet-delta9184-ar-pr-dst": [
    "/product-catalog/doc-pages/faucet-delta9184-ar-pr-dst/page-1.png",
    "/product-catalog/doc-pages/faucet-delta9184-ar-pr-dst/page-2.png"
  ],
  "faucet-moen-6702-bl": [
    "/product-catalog/doc-pages/faucet-moen-6702-bl/page-1.png",
    "/product-catalog/doc-pages/faucet-moen-6702-bl/page-2.png"
  ],
  "faucet-moen-6901bl": [
    "/product-catalog/doc-pages/faucet-moen-6901bl/page-1.png",
    "/product-catalog/doc-pages/faucet-moen-6901bl/page-2.png"
  ],
  "faucet-moen-7864-orb": [
    "/product-catalog/doc-pages/faucet-moen-7864-orb/page-1.png"
  ],
  "faucet-moen-7864srs": [
    "/product-catalog/doc-pages/faucet-moen-7864srs/page-1.png"
  ],
  "faucet-moen-87918bzg": [
    "/product-catalog/doc-pages/faucet-moen-87918bzg/page-1.png"
  ],
  "faucet-moen-s53004": [
    "/product-catalog/doc-pages/faucet-moen-s53004/page-1.png"
  ],
  "kansas-1512um18-2": [
    "/product-catalog/doc-pages/kansas-1512um18-2/page-1.png"
  ],
  "kansas-1518um18-3": [
    "/product-catalog/doc-pages/kansas-1518um18-3/page-1.png"
  ],
  "kansas-2317um18-4": [
    "/product-catalog/doc-pages/kansas-2317um18-4/page-1.png"
  ],
  "kansas-3018um16-6": [
    "/product-catalog/doc-pages/kansas-3018um16-6/page-1.png"
  ],
  "kansas-3018um18ada-9": [
    "/product-catalog/doc-pages/kansas-3018um18ada-9/page-1.png"
  ],
  "kansas-3218um16-60-40-14": [
    "/product-catalog/doc-pages/kansas-3218um16-60-40-14/page-1.png"
  ],
  "kansas-3218um18-60-40-17": [
    "/product-catalog/doc-pages/kansas-3218um18-60-40-17/page-1.png"
  ],
  "kansas-3218um18-ss-18": [
    "/product-catalog/doc-pages/kansas-3218um18-ss-18/page-1.png"
  ],
  "kansas-3221um16-60-40-21": [
    "/product-catalog/doc-pages/kansas-3221um16-60-40-21/page-1.png"
  ],
  "kansas-3221um18-60-40-22": [
    "/product-catalog/doc-pages/kansas-3221um18-60-40-22/page-1.png"
  ],
  "kansas-3221um18r-40-60-23": [
    "/product-catalog/doc-pages/kansas-3221um18r-40-60-23/page-1.png"
  ],
  "kansas-r10-ss-bl-r103219um18black-24": [
    "/product-catalog/doc-pages/kansas-r10-ss-bl-r103219um18black-24/page-1.png"
  ],
  "kansas-r15-50-50um18-27": [
    "/product-catalog/doc-pages/kansas-r15-50-50um18-27/page-1.png"
  ],
  "kansas-r15-60-40um18-28": [
    "/product-catalog/doc-pages/kansas-r15-60-40um18-28/page-1.png"
  ],
  "kansas-vc1512-oval-white-34": [
    "/product-catalog/doc-pages/kansas-vc1512-oval-white-34/page-1.png"
  ],
  "kansas-vc1613-oval-white-36": [
    "/product-catalog/doc-pages/kansas-vc1613-oval-white-36/page-1.png"
  ],
  "kansas-vc1638-rect-white-37": [
    "/product-catalog/doc-pages/kansas-vc1638-rect-white-37/page-1.png"
  ],
  "kansas-vc1912-rect-white-39": [
    "/product-catalog/doc-pages/kansas-vc1912-rect-white-39/page-1.png"
  ],
  "kansas-ws32-ss-wsum18-41": [
    "/product-catalog/doc-pages/kansas-ws32-ss-wsum18-41/page-1.png"
  ]
};
