import type { SlabAITool } from "../types";
import {
  buildMachineTroubleshooterPrompt,
  MACHINE_TROUBLESHOOTER_PROMPT_VERSION,
  machineTroubleshooterSystemPrompt,
} from "./prompt";
import { machineTroubleshooterSchema } from "./schema";

export const machineTroubleshooterTool: SlabAITool = {
  id: "machine-troubleshooter",
  slug: "machine-troubleshooter",
  title: "Bridge Saw & CNC Troubleshooter",
  shortDescription: "Safe diagnostic assistant for chipping, wandering, finish, and tooling issues.",
  description:
    "Helps operators diagnose bridge saw and CNC problems with ranked causes, safe checks, material considerations, and escalation guidance. Never invents authoritative machine setpoints and never bypasses safety systems.",
  category: "shop-operations",
  keywords: [
    "cnc",
    "bridge saw",
    "chipping",
    "blade",
    "troubleshoot",
    "quartz",
    "porcelain",
    "feed rate",
    "polishing",
  ],
  icon: "Wrench",
  modelClass: "reasoning",
  safetyClass: "machine-guidance",
  status: "live",
  featured: true,
  fields: [
    { name: "manufacturer", label: "Machine manufacturer", type: "text", required: true, placeholder: "e.g. Breton, Park Industries" },
    { name: "model", label: "Machine model", type: "text", required: true },
    {
      name: "machineType",
      label: "Machine type",
      type: "select",
      required: true,
      options: [
        { value: "bridge-saw", label: "Bridge saw" },
        { value: "cnc", label: "CNC" },
        { value: "waterjet", label: "Waterjet" },
        { value: "other", label: "Other" },
      ],
    },
    { name: "material", label: "Material", type: "text", required: true, placeholder: "e.g. Quartz, Quartzite, Porcelain" },
    { name: "materialThickness", label: "Material thickness", type: "text", required: true, placeholder: "e.g. 3 cm" },
    { name: "bladeOrTool", label: "Blade / tool", type: "text", required: true, placeholder: "Blade brand/type or CNC tool" },
    { name: "bladeDiameter", label: "Blade diameter (if known)", type: "text", placeholder: "e.g. 16 in" },
    { name: "operation", label: "Operation", type: "text", required: true, placeholder: "Straight cut, miter, polish pass…" },
    {
      name: "symptom",
      label: "Symptom",
      type: "select",
      required: true,
      options: [
        { value: "quartz-chipping", label: "Quartz chipping" },
        { value: "quartzite-deflection", label: "Quartzite deflection" },
        { value: "porcelain-chipping", label: "Porcelain chipping" },
        { value: "miter-breakout", label: "Miter breakout" },
        { value: "blade-wandering", label: "Blade wandering" },
        { value: "poor-cut-finish", label: "Poor cut finish" },
        { value: "excessive-blade-wear", label: "Excessive blade wear" },
        { value: "tool-marks", label: "Tool marks" },
        { value: "cnc-polishing-problem", label: "CNC polishing problem" },
        { value: "other", label: "Other" },
      ],
    },
    {
      name: "currentRpm",
      label: "Current RPM (if known)",
      type: "text",
      helpText: "Operator-reported only. AI will not treat this as an authoritative setpoint.",
    },
    {
      name: "currentFeedRate",
      label: "Current feed rate (if known)",
      type: "text",
      helpText: "Operator-reported only. Verify against manufacturer/tooling specs.",
    },
    { name: "waterCondition", label: "Water condition / pressure notes", type: "text" },
    { name: "recentMaintenance", label: "Recent maintenance", type: "textarea" },
    {
      name: "operatorObservations",
      label: "Operator observations",
      type: "textarea",
      required: true,
      placeholder: "When it started, sound/vibration, edge quality, photo notes…",
    },
  ],
  formSchema: machineTroubleshooterSchema,
  outputFormat: "markdown-sections",
  promptVersion: MACHINE_TROUBLESHOOTER_PROMPT_VERSION,
  systemPrompt: machineTroubleshooterSystemPrompt,
  buildPrompt: buildMachineTroubleshooterPrompt,
  evidencePolicy:
    "No fabricated machine setpoints. Prefer verification language. Escalate to supervisor/maintenance/OEM when needed.",
  relatedTools: [],
  allowedActions: [],
  knowledgeEnabled: true,
  knowledgeSourceTypes: ["sop", "machine_manual", "tooling_manual", "safety"],
  emptyStateHint:
    "Receive ranked causes, safe immediate checks, material notes, a diagnostic sequence, and escalation guidance — without invented RPM/feed specs.",
};
