import type { SlabAITool } from "../types";
import { buildRemnantPitchPrompt, REMNANT_PITCH_PROMPT_VERSION, remnantPitchSystemPrompt } from "./prompt";
import { REMNANT_APPLICATION_OPTIONS, remnantPitchSchema } from "./schema";

export const remnantPitchTool: SlabAITool = {
  id: "remnant-pitch",
  slug: "remnant-pitch",
  title: "Remnant Marketing Generator",
  shortDescription: "Turn leftover slabs into retail listings, social posts, and sales outreach.",
  description:
    "Helps remnant and sales teams convert leftover material into sellable opportunities with dimension-aware application ideas and professional marketing copy. Does not invent pricing.",
  category: "sales-estimating",
  keywords: [
    "remnant",
    "marketing",
    "sales",
    "listing",
    "social",
    "email",
    "leftover",
    "slab",
  ],
  icon: "Gem",
  modelClass: "fast",
  safetyClass: "normal",
  status: "live",
  featured: true,
  fields: [
    {
      name: "materialType",
      label: "Material type",
      type: "select",
      required: true,
      options: [
        { value: "Quartz", label: "Quartz" },
        { value: "Granite", label: "Granite" },
        { value: "Marble", label: "Marble" },
        { value: "Quartzite", label: "Quartzite" },
        { value: "Porcelain", label: "Porcelain" },
        { value: "Solid Surface", label: "Solid surface" },
        { value: "Other", label: "Other" },
      ],
    },
    {
      name: "manufacturer",
      label: "Manufacturer / brand",
      type: "text",
      placeholder: "e.g. Cambria, Cosentino, MSI",
    },
    {
      name: "colorName",
      label: "Color / name",
      type: "text",
      required: true,
      placeholder: "e.g. Calacatta Laza",
    },
    {
      name: "lengthIn",
      label: "Length (inches)",
      type: "number",
      required: true,
      min: 1,
      max: 200,
      step: 0.25,
    },
    {
      name: "widthIn",
      label: "Width (inches)",
      type: "number",
      required: true,
      min: 1,
      max: 200,
      step: 0.25,
    },
    {
      name: "thickness",
      label: "Thickness",
      type: "select",
      required: true,
      options: [
        { value: '2 cm', label: "2 cm" },
        { value: '3 cm', label: "3 cm" },
        { value: '1.2 cm', label: "1.2 cm" },
        { value: "Other", label: "Other" },
      ],
    },
    {
      name: "finish",
      label: "Finish",
      type: "select",
      required: true,
      options: [
        { value: "Polished", label: "Polished" },
        { value: "Honed", label: "Honed" },
        { value: "Leathered", label: "Leathered" },
        { value: "Matte", label: "Matte" },
        { value: "Other", label: "Other" },
      ],
    },
    {
      name: "colorPalette",
      label: "Color palette",
      type: "text",
      placeholder: "Warm whites, soft gray veining…",
      helpText: "Optional notes for marketing tone.",
    },
    {
      name: "quantity",
      label: "Approximate quantity",
      type: "number",
      required: true,
      min: 1,
      max: 50,
      step: 1,
    },
    {
      name: "possibleApplication",
      label: "Possible application focus",
      type: "select",
      required: true,
      options: [...REMNANT_APPLICATION_OPTIONS],
    },
    {
      name: "notes",
      label: "Additional notes",
      type: "textarea",
      placeholder: "Edge chips, bookmatch leftover, showroom location…",
    },
  ],
  formSchema: remnantPitchSchema,
  outputFormat: "markdown-sections",
  promptVersion: REMNANT_PITCH_PROMPT_VERSION,
  systemPrompt: remnantPitchSystemPrompt,
  buildPrompt: buildRemnantPitchPrompt,
  evidencePolicy: "Dimension reasoning from user inputs only. No inventing price or inventory status.",
  relatedTools: ["quote-scope"],
  allowedActions: [],
  knowledgeEnabled: false,
  emptyStateHint:
    "Generate an opportunity summary, retail listing, social post, sales email, and dimension-aware application ideas.",
};
