/**
 * Deterministic synthetic countertop plan PDF generator (Phase 4B.4A).
 *
 * Pure Node — no Gemini, no network. Produces a valid single-page PDF with
 * fictional Elite Kitchen Lab geometry for loopback live-takeoff testing.
 *
 * Usage (from app-quote-intake-lab):
 *   node fixtures/takeoff/generateSyntheticPlanPdf.mjs
 *
 * Writes:
 *   fixtures/takeoff/qil-synth-kitchen-island-plan.pdf
 *   fixtures/takeoff/qil-synth-kitchen-island-plan.ground-truth.json (hash refreshed)
 */

import { createHash } from "node:crypto";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PDF_NAME = "qil-synth-kitchen-island-plan.pdf";
const GT_NAME = "qil-synth-kitchen-island-plan.ground-truth.json";

/** Known geometry — matches ground-truth JSON. */
export const SYNTH_PLAN_GEOMETRY = Object.freeze({
  fixtureId: "qil-synth-kitchen-island-plan",
  projectName: "Synthetic Quote Intake Lab Fixture — Maple Court Kitchen",
  customer: "Example Homes LLC (synthetic)",
  address: "100 Example Way, Exampleville, EX 00000",
  labelBanner: "SYNTHETIC QUOTE INTAKE LAB FIXTURE — NOT A REAL CUSTOMER PLAN",
  mainRun: { label: "Main run", lengthIn: 120, depthIn: 25.5, measuredSf: 21.25 },
  island: { label: "Island", lengthIn: 72, depthIn: 36, measuredSf: 18 },
  sink: { label: "Sink cutout", count: 1, note: "One undermount sink on main run (count only — not deducted from SF)" },
  backsplash: {
    scope: "standard",
    linearIn: 120,
    heightIn: 4,
    measuredSf: 3.33,
    note: "Standard 4 in backsplash along the 120 in main run"
  },
  writtenTotalNote: "Written plan total (recon only): Countertop 39.25 SF + Backsplash ~3.33 SF = ~42.58 SF combined",
  expected: {
    countertopSf: 39.25,
    backsplashSf: 3.33,
    combinedSf: 42.58,
    sinkCount: 1
  },
  toleranceSf: 0.05
});

/**
 * Build a minimal valid PDF 1.4 (single letter page, Helvetica text, simple rectangles).
 * Fixed object layout so bytes stay stable for a given geometry blob.
 */
export function buildSyntheticKitchenIslandPdfBytes() {
  const g = SYNTH_PLAN_GEOMETRY;
  const lines = [
    "SYNTHETIC QUOTE INTAKE LAB FIXTURE",
    "NOT A REAL CUSTOMER PLAN — example.com identities only",
    "",
    `Project: ${g.projectName}`,
    `Customer: ${g.customer}`,
    `Address: ${g.address}`,
    "",
    "KITCHEN PLAN — PAGE 1 OF 1",
    "",
    "MAIN RUN (countertop):",
    `  Length: ${g.mainRun.lengthIn} in`,
    `  Depth: ${g.mainRun.depthIn} in`,
    `  Area (labeled): ${g.mainRun.measuredSf} SF`,
    "",
    "ISLAND (countertop):",
    `  Length: ${g.island.lengthIn} in`,
    `  Depth: ${g.island.depthIn} in`,
    `  Area (labeled): ${g.island.measuredSf} SF`,
    "",
    "SINK CUTOUT:",
    `  Count: ${g.sink.count}`,
    `  Note: ${g.sink.note}`,
    "",
    "STANDARD BACKSPLASH:",
    `  Scope: ${g.backsplash.scope}`,
    `  Linear: ${g.backsplash.linearIn} in along main run`,
    `  Height: ${g.backsplash.heightIn} in`,
    `  Area (labeled): approximately ${g.backsplash.measuredSf} SF`,
    "",
    "WRITTEN TOTALS (for reconciliation — not AI authority):",
    `  Countertop total: ${g.expected.countertopSf} SF`,
    `  Backsplash total: approximately ${g.expected.backsplashSf} SF`,
    `  Combined stated: approximately ${g.expected.combinedSf} SF`,
    `  Sink count: ${g.expected.sinkCount}`,
    "",
    "Geometry sketch (schematic inches, not to CAD scale):",
    "  Main run  [================ 120 in =================] x 25.5 in",
    "            (sink cutout marked on main run)",
    "  Island    [======= 72 in =======] x 36 in",
    "  Splash    4 in height along 120 in main run",
    "",
    "This PDF has no scripts, forms, or active content.",
    "Generated by Quote Intake Lab fixtures/takeoff/generateSyntheticPlanPdf.mjs"
  ];

  const contentStream = buildContentStream(lines);
  return assemblePdf(contentStream);
}

function escapePdfText(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildContentStream(lines) {
  const ops = [];
  ops.push("BT");
  ops.push("/F1 11 Tf");
  ops.push("50 750 Td");
  ops.push("14 TL");
  for (let i = 0; i < lines.length; i++) {
    const t = escapePdfText(lines[i] || " ");
    if (i === 0) {
      ops.push(`(${t}) Tj`);
    } else {
      ops.push(`T* (${t}) Tj`);
    }
  }
  ops.push("ET");
  // Simple schematic rectangles (page coords, bottom-left origin)
  ops.push("1.5 w");
  // Main run rectangle
  ops.push("50 120 400 40 re S");
  // Island rectangle
  ops.push("50 60 240 50 re S");
  return ops.join("\n") + "\n";
}

function assemblePdf(streamText) {
  const objects = [];
  const add = (body) => {
    objects.push(body);
    return objects.length;
  };

  const fontId = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const contentId = add(`<< /Length ${Buffer.byteLength(streamText, "utf8")} >>\nstream\n${streamText}endstream`);
  const resourcesId = add(`<< /Font << /F1 ${fontId} 0 R >> >>`);
  const pageId = add(
    `<< /Type /Page /Parent 0 0 R /MediaBox [0 0 612 792] /Contents ${contentId} 0 R /Resources ${resourcesId} 0 R >>`
  );
  const pagesId = add(`<< /Type /Pages /Kids [${pageId} 0 R] /Count 1 >>`);
  // Fix parent reference on page
  objects[pageId - 1] =
    `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Contents ${contentId} 0 R /Resources ${resourcesId} 0 R >>`;
  const catalogId = add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);

  let pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
  const offsets = [0];
  for (let i = 0; i < objects.length; i++) {
    offsets.push(Buffer.byteLength(pdf, "latin1"));
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefPos = Buffer.byteLength(pdf, "latin1");
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= objects.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\n`;
  pdf += `startxref\n${xrefPos}\n%%EOF\n`;
  return Buffer.from(pdf, "latin1");
}

export function sha256Hex(buf) {
  return createHash("sha256").update(buf).digest("hex");
}

export function buildGroundTruth(contentHash, sizeBytes) {
  const g = SYNTH_PLAN_GEOMETRY;
  return {
    schemaVersion: "qil_synth_plan_ground_truth_v1",
    fixtureId: g.fixtureId,
    filename: PDF_NAME,
    mimeType: "application/pdf",
    contentHash,
    sizeBytes,
    project: {
      name: g.projectName,
      customer: g.customer,
      address: g.address,
      synthetic: true,
      banner: g.labelBanner
    },
    pages: [{ pageNumber: 1, role: "plan" }],
    rooms: [
      {
        id: "qil-room-kitchen",
        name: "Kitchen",
        pieces: [
          {
            id: "qil-piece-main-run",
            label: g.mainRun.label,
            lengthIn: g.mainRun.lengthIn,
            depthIn: g.mainRun.depthIn,
            shape: "rect",
            pieceType: "counter",
            measuredSf: g.mainRun.measuredSf,
            cutouts: [{ type: "sink", label: "Undermount sink" }]
          },
          {
            id: "qil-piece-island",
            label: g.island.label,
            lengthIn: g.island.lengthIn,
            depthIn: g.island.depthIn,
            shape: "rect",
            pieceType: "counter",
            measuredSf: g.island.measuredSf,
            cutouts: []
          }
        ],
        backsplash: {
          scope: g.backsplash.scope,
          linearIn: g.backsplash.linearIn,
          heightIn: g.backsplash.heightIn,
          measuredSf: g.backsplash.measuredSf
        }
      }
    ],
    expected: {
      countertopSf: g.expected.countertopSf,
      backsplashSf: g.expected.backsplashSf,
      combinedSf: g.expected.combinedSf,
      sinkCount: g.expected.sinkCount
    },
    toleranceSf: g.toleranceSf,
    notes: [
      "Fictional plan for Quote Intake Lab live takeoff foundation tests.",
      "No real customer information.",
      "Sink cutouts are count-only and must never be deducted from measured SF.",
      "eliteOS deterministic calc is authoritative for measured SF."
    ]
  };
}

function main() {
  const bytes = buildSyntheticKitchenIslandPdfBytes();
  const hash = sha256Hex(bytes);
  const pdfPath = join(__dirname, PDF_NAME);
  const gtPath = join(__dirname, GT_NAME);
  writeFileSync(pdfPath, bytes);
  writeFileSync(gtPath, JSON.stringify(buildGroundTruth(hash, bytes.length), null, 2) + "\n");
  console.log(`[qil-synth-plan] wrote ${PDF_NAME} (${bytes.length} bytes)`);
  console.log(`[qil-synth-plan] sha256=${hash}`);
  console.log(`[qil-synth-plan] wrote ${GT_NAME}`);
  // Soft open check: %PDF header
  const head = bytes.subarray(0, 5).toString("utf8");
  if (head !== "%PDF-") throw new Error("Generated file missing %PDF- header");
  if (existsSync(gtPath)) {
    const gt = JSON.parse(readFileSync(gtPath, "utf8"));
    if (gt.contentHash !== hash) throw new Error("Ground-truth hash mismatch after write");
  }
}

const isMain =
  process.argv[1] &&
  fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) main();
