import type { SlabAITool } from "../types";
import { buildQuoteScopePrompt, QUOTE_SCOPE_PROMPT_VERSION, quoteScopeSystemPrompt } from "./prompt";
import { quoteScopeSchema } from "./schema";

export const quoteScopeTool: SlabAITool = {
  id: "quote-scope",
  slug: "quote-scope",
  title: "Quote & Fabrication Scope Drafter",
  shortDescription: "Draft professional scope narratives — never invents pricing.",
  description:
    "Produces customer-ready fabrication scope language: included work, assumptions, exclusions, and a proposal narrative. Does not calculate prices and does not replace eliteOS quote calculators.",
  category: "sales-estimating",
  keywords: [
    "quote",
    "scope",
    "proposal",
    "fabrication",
    "estimating",
    "exclusions",
    "assumptions",
  ],
  icon: "FileText",
  modelClass: "reasoning",
  safetyClass: "operational",
  status: "live",
  featured: true,
  fields: [
    { name: "customerProjectName", label: "Customer / project name", type: "text", required: true },
    {
      name: "projectType",
      label: "Project type",
      type: "select",
      required: true,
      options: [
        { value: "residential-kitchen", label: "Residential kitchen" },
        { value: "residential-bath", label: "Residential bath" },
        { value: "commercial", label: "Commercial" },
        { value: "remodel", label: "Remodel" },
        { value: "new-construction", label: "New construction" },
        { value: "other", label: "Other" },
      ],
    },
    { name: "roomArea", label: "Room / area", type: "text", required: true, placeholder: "Kitchen island + perimeter" },
    {
      name: "approximateSqFt",
      label: "Approximate square footage",
      type: "number",
      min: 1,
      max: 50000,
      step: 0.5,
      helpText: "Optional. Used for narrative context only — not for pricing math.",
    },
    { name: "materialColor", label: "Material / color", type: "text", required: true },
    { name: "materialGroup", label: "Material group / tier", type: "text", placeholder: "Optional" },
    {
      name: "thickness",
      label: "Thickness",
      type: "select",
      required: true,
      options: [
        { value: "2 cm", label: "2 cm" },
        { value: "3 cm", label: "3 cm" },
        { value: "Other", label: "Other" },
      ],
    },
    { name: "edgeProfile", label: "Edge profile", type: "text", required: true, placeholder: "e.g. Eased, Ogee, Dupont" },
    { name: "sinkCutouts", label: "Sink cutouts", type: "number", required: true, min: 0, max: 20, step: 1 },
    { name: "cooktopCutouts", label: "Cooktop cutouts", type: "number", required: true, min: 0, max: 10, step: 1 },
    { name: "faucetHoles", label: "Faucet holes", type: "number", required: true, min: 0, max: 20, step: 1 },
    { name: "backsplash", label: "Backsplash", type: "text", placeholder: "4\" splash / full height / none" },
    { name: "waterfallPanels", label: "Waterfall panels", type: "text" },
    { name: "tearOut", label: "Tear-out included", type: "checkbox" },
    { name: "templateRequired", label: "Template required", type: "checkbox" },
    { name: "installationRequired", label: "Installation required", type: "checkbox" },
      { name: "customerSuppliedItems", label: "Customer-supplied items", type: "textarea", placeholder: "Sink, faucet, cooktop…" },
      { name: "projectNotes", label: "Project notes", type: "textarea" },
      {
        name: "loadedQuoteId",
        label: "Loaded quote ID (optional)",
        type: "text",
        placeholder: "Paste quote UUID from search",
        helpText: "Use Load existing quote, or paste a governed quote UUID. AI drafts narrative only — does not change the quote.",
      },
      {
        name: "loadedAccountId",
        label: "Loaded account ID (optional)",
        type: "text",
        placeholder: "Account Directory UUID after search/select",
        helpText: "Requires Account Directory access. Ambiguous names must be selected — IDs define relationships.",
      },
    ],
    formSchema: quoteScopeSchema,
  outputFormat: "markdown-sections",
  promptVersion: QUOTE_SCOPE_PROMPT_VERSION,
  systemPrompt: quoteScopeSystemPrompt,
  buildPrompt: buildQuoteScopePrompt,
  evidencePolicy: "Narrative scope only. Pricing authority remains eliteOS Brain calculators.",
  relatedTools: ["remnant-pitch", "stone-care", "account-brief"],
  allowedActions: ["retrieveQuote", "searchQuotes", "searchAccounts", "retrieveAccount"],
  knowledgeEnabled: true,
  knowledgeSourceTypes: ["quote_policy", "sales_policy", "install_standard", "sop"],
  emptyStateHint:
    "Draft included scope, fabrication/install language, assumptions, exclusions, and a customer-friendly proposal narrative — with no invented prices.",
};
