import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const workspace = readFileSync(join(here, "../ui/FinanceWorkspace.tsx"), "utf8");
const commandCenter = readFileSync(join(here, "../ui/FinanceCommandCenter.tsx"), "utf8");
const charts = readFileSync(join(here, "../ui/FinanceCharts.tsx"), "utf8");
const motion = readFileSync(join(here, "../ui/financeMotion.tsx"), "utf8");
const drilldown = readFileSync(join(here, "../ui/FinanceDrilldown.tsx"), "utf8");
const drilldownContent = readFileSync(join(here, "../ui/FinanceDrilldownContent.tsx"), "utf8");
const styles = readFileSync(join(here, "../ui/styles.css"), "utf8");
const app = readFileSync(join(here, "../ui/App.tsx"), "utf8");
const supabase = readFileSync(join(here, "supabase.ts"), "utf8");

assert.ok(app.includes("EliteosTopbar"));
assert.equal(app.includes("searchSlot"), false);
assert.equal(workspace.includes("qb_finance_"), false);
assert.equal(workspace.includes("from(\"qb_"), false);
assert.equal(supabase.includes("SERVICE_ROLE"), false);
assert.equal(supabase.includes("service_role"), false);
assert.ok(workspace.includes("/api/finance/overview"));
assert.equal(workspace.includes("JSON.stringify((ar.aging"), false);
assert.equal(workspace.includes("fin-pre"), false);
assert.ok(commandCenter.includes("agingRowsFromBuckets"));
assert.ok(commandCenter.includes("cashEventRoleLabel"));
assert.ok(commandCenter.includes("formatPeriodCaption"));
assert.ok(commandCenter.includes("recent_activity"));
assert.equal(commandCenter.includes("role.event_role.replace"), false);
assert.ok(commandCenter.includes('onOpen("revenue")'));
assert.ok(commandCenter.includes('onOpen("gross_margin")'));
assert.ok(commandCenter.includes('onOpen("ar")'));
assert.ok(commandCenter.includes('onOpen("cash")'));
assert.ok(commandCenter.includes('onOpen("balance_sheet")'));
assert.ok(commandCenter.includes("/api/finance/ar/invoices"));
assert.ok(commandCenter.includes("/api/finance/ap/bills"));
assert.ok(commandCenter.includes("/api/finance/accounts"));
assert.ok(commandCenter.includes("/api/finance/journal-entries"));
assert.ok(commandCenter.includes("/api/finance/transaction-activity"));
assert.ok(commandCenter.includes("YTD totals combine the monthly QuickBooks statements above."));
assert.ok(drilldown.includes('role="dialog"'));
assert.ok(drilldown.includes('aria-modal="true"'));
assert.ok(drilldown.includes('event.key === "Escape"'));
assert.ok(drilldown.includes('event.key !== "Tab"'));
assert.ok(drilldown.includes("priorFocus?.focus({ preventScroll: true })"));
assert.ok(drilldown.includes('document.body.style.position = "fixed"'));
assert.ok(drilldown.includes('className="fin-drilldown-scroll" tabIndex={0}'));
assert.ok(drilldown.includes('event.key === "PageDown"'));
assert.ok(drilldownContent.includes("buildPnlInsights"));
assert.ok(drilldownContent.includes("buildArInsights"));
assert.ok(drilldownContent.includes("cashEventRoleLabel(role.event_role)"));
assert.ok(drilldownContent.includes("Customer receipts + bank deposits"));
assert.ok(drilldownContent.includes("DueDate coverage"));
assert.ok(motion.includes("IntersectionObserver"));
assert.ok(motion.includes("motionIsReduced()"));
assert.ok(motion.includes("completedMotionKeys"));
assert.ok(motion.includes("progress === 1 ? exact : exact * eased"));
assert.ok(motion.includes("aria-label={finalLabel}"));
assert.ok(charts.includes("useViewportOnce"));
assert.ok(charts.includes("aria-label={`${formatYmdUtc(coord.source.period_start)}"));
assert.ok(styles.includes("@media (prefers-reduced-motion: reduce)"));
assert.ok(styles.includes(".fin-drilldown"));
assert.ok(styles.includes(".fin-reveal"));
assert.ok(styles.includes("overflow-y: auto"));
assert.ok(styles.includes("touch-action: pan-y"));
assert.equal(styles.includes("Georgia"), false);
assert.equal(styles.includes("Geist"), false);
console.log("financeUiSafety.test.mjs: ok");
