import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const workspace = readFileSync(join(here, "../ui/FinanceWorkspace.tsx"), "utf8");
const drilldown = readFileSync(join(here, "../ui/FinanceDrilldown.tsx"), "utf8");
const drilldownContent = readFileSync(join(here, "../ui/FinanceDrilldownContent.tsx"), "utf8");
const styles = readFileSync(join(here, "../ui/styles.css"), "utf8");
const app = readFileSync(join(here, "../ui/App.tsx"), "utf8");
const supabase = readFileSync(join(here, "supabase.ts"), "utf8");

assert.ok(app.includes("EliteosTopbar"));
assert.equal(app.includes("searchSlot"), false);
assert.equal(workspace.includes("qb_finance_"), false);
assert.equal(workspace.includes("from(\"qb_"), false);
assert.equal(supabase.includes("SERVICE_ROLE"), false);
assert.equal(supabase.includes("service_role"), false);
assert.ok(workspace.includes("/api/finance/overview"));
assert.equal(workspace.includes("JSON.stringify((ar.aging"), false);
assert.equal(workspace.includes("fin-pre"), false);
assert.ok(workspace.includes("agingRowsFromBuckets"));
assert.ok(workspace.includes("cashEventRoleLabel"));
assert.ok(workspace.includes("formatPeriodCaption"));
assert.ok(workspace.includes("recent_checks"));
assert.equal(workspace.includes("role.event_role.replace"), false);
assert.ok(workspace.includes('openDrilldown("revenue")'));
assert.ok(workspace.includes('openDrilldown("gross_margin")'));
assert.ok(workspace.includes('openDrilldown("ar")'));
assert.ok(workspace.includes('openDrilldown("cash")'));
assert.ok(workspace.includes('openDrilldown("balance_sheet")'));
assert.ok(drilldown.includes('role="dialog"'));
assert.ok(drilldown.includes('aria-modal="true"'));
assert.ok(drilldown.includes('event.key === "Escape"'));
assert.ok(drilldown.includes('event.key !== "Tab"'));
assert.ok(drilldown.includes("priorFocus?.focus()"));
assert.ok(drilldownContent.includes("buildPnlInsights"));
assert.ok(drilldownContent.includes("buildArInsights"));
assert.ok(drilldownContent.includes("cashEventRoleLabel(role.event_role)"));
assert.ok(drilldownContent.includes("Customer receipts + bank deposits"));
assert.ok(drilldownContent.includes("DueDate coverage"));
assert.ok(styles.includes("@media (prefers-reduced-motion: reduce)"));
assert.ok(styles.includes(".fin-drilldown"));
assert.ok(styles.includes(".fin-motion-ready"));
console.log("financeUiSafety.test.mjs: ok");
